import type { ScenarioInputs } from '../calculator/types'

export const STORAGE_KEY = 'fortuna.scenario.v1'
export const SCHEMA_VERSION = 2

export const defaultScenario: ScenarioInputs = {
  schemaVersion: SCHEMA_VERSION,
  birthMonth: 4,
  birthYear: 1943,
  endAge: 95,
  single: true,
  homeowner: true,
  startingCash: 1_600_000,
  homeValue: 600_000,
  homePurchasePrice: 600_000,
  homeTransactionCosts: 0,
  homeRenovations: 0,
  homeGrowthPct: 3.5,
  homeSaleAge: null,
  setupExpenses: 0,
  prepaidFuneral: 0,
  cemeteryPlot: 0,
  prepaidItems: [],
  giftingYears: [10_000, 10_000, 10_000],
  assessableTarget: 1_600_000,
  annuityAllocationPct: 0,
  vdcoOfRemainderPct: 0,
  bondOfRemainderPct: 0,
  cashReserveMonths: 9,
  annualSpendingTarget: 50_000,
  creditCardLimit: 3_000,
  irregularExpenseAllowance: 5_000,
  inflationPct: 3.5,
  thresholdIndexationPct: 3.5,
  vdcoYieldPct: 2.5,
  vdcoGrowthPct: 4.0,
  vdcoFeePct: 0.27,
  bond: {
    faceValue: 100_000,
    purchasePrice: 100_000,
    couponRatePct: 5.3,
    yieldToMaturityPct: 5.3,
    yearsToMaturity: 10,
    sellBeforeMaturity: false,
    salePrice: 100_000,
  },
  annuityPayoutPer100k: 9_970,
  annuityAssessableAssetStartPct: 60,
  annuityAssessableAssetAfterPct: 30,
  annuityAssessableIncomePct: 60,
  runToZero: false,
  agedCareEnabled: false,
  agedCareStartAge: 95,
  agedCareHomeSold: false,
  protectedPersonInHome: false,
  agedCareAccommodationAnnual: 0,
  agedCareMeansTestedAnnual: 0,
  superBalance: 25_000,
  downsizerContribution: 0,
  frankingPct: 70,
  mode: 'balanced',
}
